[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/forms"
  to = "/.netlify/functions/forms"
  status = 200

[[redirects]]
  from = "/api/forms/*"
  to = "/.netlify/functions/forms/:splat"
  status = 200

[[redirects]]
  from = "/api/responses"
  to = "/.netlify/functions/responses"
  status = 200

[[redirects]]
  from = "/api/responses/*"
  to = "/.netlify/functions/responses/:splat"
  status = 200

[[redirects]]
  from = "/api/stats/*"
  to = "/.netlify/functions/stats/:splat"
  status = 200

[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/upload"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
